# OpenAPI 3.0 Beispiel f체r den Zoom-Webhook-Endpunkt
openapi: 3.0.3
info:
  title: Zoom Webhook Serviceware API
  version: 1.0.0
  description: API-Dokumentation f체r den Zoom-Webhook-Serviceware-Proxy
servers:
  - url: http://localhost:3000
paths:
  /zoom-phone-call-events:
    post:
      summary: Empf채ngt Zoom Phone Webhook Events
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WebHookBody'
      responses:
        '200':
          description: Event verarbeitet
        '401':
          description: Signatur ung체ltig
  /health:
    get:
      summary: Healthcheck
      responses:
        '200':
          description: OK
components:
  schemas:
    WebHookBody:
      type: object
      properties:
        event:
          type: string
        payload:
          type: object
